// <auto-generated />
namespace Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Add_seed_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_seed_data));
        
        string IMigrationMetadata.Id
        {
            get { return "202601161242585_Add_seed_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
