// <auto-generated />
namespace Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Correct_Issue_Issuetype_relation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Correct_Issue_Issuetype_relation));
        
        string IMigrationMetadata.Id
        {
            get { return "202601131324439_Correct_Issue_Issuetype_relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
